---
services:
  bind9:
    container_name: home-dns
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Europe/Paris
    ports:
      - "1053:53/tcp"
      - "1053:53/udp"
    volumes:
      - ${DNS_CONFIG_PATH}/config:/etc/bind
      - ${DNS_CONFIG_PATH}/cache:/var/cache/bind
      - ${DNS_CONFIG_PATH}/records:/var/lib/bind
    restart: always