---
services:
  traefik:
    image: traefik:v3.4
    container_name: traefik
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Volumes/docker/traefik/config/traefik.yaml:/etc/traefik/traefik.yaml:ro
    restart: unless-stopped
    networks:
      - frontend
networks:
  frontend:
    external: true